/* export const ADMIN_INFOS_REQUEST = 'ADMIN_INFOS_REQUEST'
export const ADMIN_INFOS_SUCCESS = 'ADMIN_INFOS_SUCCESS'
export const ADMIN_INFOS_FAIL = 'ADMIN_INFOS_FAIL'

export const ALL_INFOS_REQUEST = 'ALL_INFOS_REQUEST'
export const ALL_INFOS_SUCCESS = 'ALL_INFOS_SUCCESS'
export const ALL_INFOS_FAIL = 'ALL_INFOS_FAIL'

export const NEW_INFOS_REQUEST = 'NEW_INFOS_REQUEST'
export const NEW_INFOS_SUCCESS = 'NEW_INFOS_SUCCESS'
export const NEW_INFOS_RESET = 'NEW_INFOS_RESET'
export const NEW_INFOS_FAIL = 'NEW_INFOS_FAIL'

export const DELETE_INFOS_REQUEST = 'DELETE_INFOS_REQUEST'
export const DELETE_INFOS_SUCCESS = 'DELETE_INFOS_SUCCESS'
export const DELETE_INFOS_RESET = 'DELETE_INFOS_RESET'
export const DELETE_INFOS_FAIL = 'DELETE_INFOS_FAIL'

export const UPDATE_INFOS_REQUEST = 'UPDATE_INFOS_REQUEST'
export const UPDATE_INFOS_SUCCESS = 'UPDATE_INFOS_SUCCESS'
export const UPDATE_INFOS_RESET = 'UPDATE_INFOS_RESET'
export const UPDATE_INFOS_FAIL = 'UPDATE_INFOS_FAIL'

export const INFOS_DETAILS_REQUEST = 'INFOS_DETAILS_REQUEST'
export const INFOS_DETAILS_SUCCESS = 'INFOS_DETAILS_SUCCESS'
export const INFOS_DETAILS_FAIL = 'INFOS_DETAILS_FAIL' */
/* export const ADMIN_INFOS_REQUEST = 'ADMIN_INFOS_REQUEST'
export const ADMIN_INFOS_SUCCESS = 'ADMIN_INFOS_SUCCESS'
export const ADMIN_INFOS_FAIL = 'ADMIN_INFOS_FAIL'

export const ALL_INFOS_REQUEST = 'ALL_INFOS_REQUEST'
export const ALL_INFOS_SUCCESS = 'ALL_INFOS_SUCCESS'
export const ALL_INFOS_FAIL = 'ALL_INFOS_FAIL'

export const NEW_INFO_REQUEST = 'NEW_INFO_REQUEST'
export const NEW_INFO_SUCCESS = 'NEW_INFO_SUCCESS'
export const NEW_INFO_RESET = 'NEW_INFO_RESET'
export const NEW_INFO_FAIL = 'NEW_INFO_FAIL'

export const DELETE_INFO_REQUEST = 'DELETE_INFO_REQUEST'
export const DELETE_INFO_SUCCESS = 'DELETE_INFO_SUCCESS'
export const DELETE_INFO_RESET = 'DELETE_INFO_RESET'
export const DELETE_INFO_FAIL = 'DELETE_INFO_FAIL'

export const UPDATE_INFO_REQUEST = 'UPDATE_INFO_REQUEST'
export const UPDATE_INFO_SUCCESS = 'UPDATE_INFO_SUCCESS'
export const UPDATE_INFO_RESET = 'UPDATE_INFO_RESET'
export const UPDATE_INFO_FAIL = 'UPDATE_INFO_FAIL'

export const INFO_DETAILS_REQUEST = 'INFO_DETAILS_REQUEST'
export const INFO_DETAILS_SUCCESS = 'INFO_DETAILS_SUCCESS'
export const INFO_DETAILS_FAIL = 'INFO_DETAILS_FAIL'


export const CLEAR_ERRORS = 'CLEAR_ERRORS' */

/* export const ADMIN_INFOS_REQUEST = 'ADMIN_INFOS_REQUEST'
export const ADMIN_INFOS_SUCCESS = 'ADMIN_INFOS_SUCCESS'
export const ADMIN_INFOS_FAIL = 'ADMIN_INFOS_FAIL'

export const ALL_INFOS_REQUEST = 'ALL_INFOS_REQUEST'
export const ALL_INFOS_SUCCESS = 'ALL_INFOS_SUCCESS'
export const ALL_INFOS_FAIL = 'ALL_INFOS_FAIL'

export const NEW_INFO_REQUEST = 'NEW_INFO_REQUEST'
export const NEW_INFO_SUCCESS = 'NEW_INFO_SUCCESS'
export const NEW_INFO_RESET = 'NEW_INFO_RESET'
export const NEW_INFO_FAIL = 'NEW_INFO_FAIL'

export const DELETE_INFO_REQUEST = 'DELETE_INFO_REQUEST'
export const DELETE_INFO_SUCCESS = 'DELETE_INFO_SUCCESS'
export const DELETE_INFO_RESET = 'DELETE_INFO_RESET'
export const DELETE_INFO_FAIL = 'DELETE_INFO_FAIL'

export const UPDATE_INFO_REQUEST = 'UPDATE_INFO_REQUEST'
export const UPDATE_INFO_SUCCESS = 'UPDATE_INFO_SUCCESS'
export const UPDATE_INFO_RESET = 'UPDATE_INFO_RESET'
export const UPDATE_INFO_FAIL = 'UPDATE_INFO_FAIL'

export const INFO_DETAILS_REQUEST = 'INFO_DETAILS_REQUEST'
export const INFO_DETAILS_SUCCESS = 'INFO_DETAILS_SUCCESS'
export const INFO_DETAILS_FAIL = 'INFO_DETAILS_FAIL'
 */
export const ADMIN_INFOS_REQUEST = 'ADMIN_INFOS_REQUEST'
export const ADMIN_INFOS_SUCCESS = 'ADMIN_INFOS_SUCCESS'
export const ADMIN_INFOS_FAIL = 'ADMIN_INFOS_FAIL'

export const ALL_INFOS_REQUEST = 'ALL_INFOS_REQUEST'
export const ALL_INFOS_SUCCESS = 'ALL_INFOS_SUCCESS'
export const ALL_INFOS_FAIL = 'ALL_INFOS_FAIL'

export const NEW_INFO_REQUEST = 'NEW_INFO_REQUEST'
export const NEW_INFO_SUCCESS = 'NEW_INFO_SUCCESS'
export const NEW_INFO_RESET = 'NEW_INFO_RESET'
export const NEW_INFO_FAIL = 'NEW_INFO_FAIL'

export const DELETE_INFO_REQUEST = 'DELETE_INFO_REQUEST'
export const DELETE_INFO_SUCCESS = 'DELETE_INFO_SUCCESS'
export const DELETE_INFO_RESET = 'DELETE_INFO_RESET'
export const DELETE_INFO_FAIL = 'DELETE_INFO_FAIL'

export const UPDATE_INFO_REQUEST = 'UPDATE_INFO_REQUEST'
export const UPDATE_INFO_SUCCESS = 'UPDATE_INFO_SUCCESS'
export const UPDATE_INFO_RESET = 'UPDATE_INFO_RESET'
export const UPDATE_INFO_FAIL = 'UPDATE_INFO_FAIL'

export const INFO_DETAILS_REQUEST = 'INFO_DETAILS_REQUEST'
export const INFO_DETAILS_SUCCESS = 'INFO_DETAILS_SUCCESS'
export const INFO_DETAILS_FAIL = 'INFO_DETAILS_FAIL'



export const CLEAR_ERRORS = 'CLEAR_ERRORS'