export const ADMIN_OFFERS_REQUEST = 'ADMIN_OFFERS_REQUEST'
export const ADMIN_OFFERS_SUCCESS = 'ADMIN_OFFERS_SUCCESS'
export const ADMIN_OFFERS_FAIL = 'ADMIN_OFFERS_FAIL'

export const ALL_OFFERS_REQUEST = 'ALL_OFFERS_REQUEST'
export const ALL_OFFERS_SUCCESS = 'ALL_OFFERS_SUCCESS'
export const ALL_OFFERS_FAIL = 'ALL_OFFERS_FAIL'

export const NEW_OFFER_REQUEST = 'NEW_OFFER_REQUEST'
export const NEW_OFFER_SUCCESS = 'NEW_OFFER_SUCCESS'
export const NEW_OFFER_RESET = 'NEW_OFFER_RESET'
export const NEW_OFFER_FAIL = 'NEW_OFFER_FAIL'

export const DELETE_OFFER_REQUEST = 'DELETE_OFFER_REQUEST'
export const DELETE_OFFER_SUCCESS = 'DELETE_OFFER_SUCCESS'
export const DELETE_OFFER_RESET = 'DELETE_OFFER_RESET'
export const DELETE_OFFER_FAIL = 'DELETE_OFFER_FAIL'

export const UPDATE_OFFER_REQUEST = 'UPDATE_OFFER_REQUEST'
export const UPDATE_OFFER_SUCCESS = 'UPDATE_OFFER_SUCCESS'
export const UPDATE_OFFER_RESET = 'UPDATE_OFFER_RESET'
export const UPDATE_OFFER_FAIL = 'UPDATE_OFFER_FAIL'

export const OFFER_DETAILS_REQUEST = 'OFFER_DETAILS_REQUEST'
export const OFFER_DETAILS_SUCCESS = 'OFFER_DETAILS_SUCCESS'
export const OFFER_DETAILS_FAIL = 'OFFER_DETAILS_FAIL'



export const CLEAR_ERRORS = 'CLEAR_ERRORS'